<?php
function _datalogger_station_status(){
	return array(
		'station_active' => 'Đang Hoạt Động',
		'station_deactive' => 'Không Hoạt Động',
		'station_error' => 'Đang Lỗi',
	);
}
/**
 * Implements hook_openlayers_styles().
 */
function datalogger_openlayers_styles(&$map) {
	/*
	$styles = array();

  $style = new stdClass();
  $style->api_version = 1;
  $style->name = 'test_style';
  $style->title = t('Default style');
  $style->description = t('Basic default style.');
  $style->data = array(
    'pointRadius' => '5', 
    'fillColor' => '#FFCC66', 
    'strokeColor' => '#FF9933', 
    'strokeWidth' => '7', 
    'fillOpacity' => '3.5',
  );
  $styles[$style->name] = $style;

	*/
	// drupal_add_js(drupal_get_path('module', 'datalogger') . '/refreshView.js');
	
	// underway = new OpenLayers.Layer.Vector("WFS", {
            // strategies: [new OpenLayers.Strategy.BBOX(), new OpenLayers.Strategy.Refresh({interval: 4000, force: true})],
            // protocol: new OpenLayers.Protocol.WFS({
                // url:  "http://root.domua.khituongthuyvan.net/view/stations",
                // featureType: "ss2011_v03",
                // featureNS: "http://csiro.au/underway",
                // geometryName: "position"
            // });
  return $map['styles'];
	// dsm($map);
}

 /**
 *Begin:15/11. 
 *Implements hook_views_form_alter().
 *Author:hungnm0302
 *Description: thay doi ket qua hien thi tren form cua view
 */	
function datalogger_form_alter(&$form, $form_state, $form_id){
	global $user;
	$account = user_load($user->uid);

	// dsm($form);
	if(!in_array('administrator', array_values($account->roles))){
		if($form_id = 'views_exposed_form'){
			if($form['#id'] == 'views-exposed-form-view-command-send-station-page' || 
				$form['#id'] == 'views-exposed-form-view-rainfall-default-page' ||
				$form['#id'] == 'views-exposed-form-search-rainfall-page' ||
				$form['#id'] == 'views-exposed-form-rainfall-chart-page' ||
				$form['#id'] == 'views-exposed-form-view-list-stations-page' ||
				$form['#id'] == 'views-exposed-form-view-station-rainfall-statistics-page' ){
				$provinces = array();
				$provinces['All'] = t('- Any -');
				$provinces = array_merge($provinces, _datalogger_return_city2($account->field_station_region['und'][0]['value']));
				
				//tram do mưa
				$region_station = $account->field_station_region['und'][0]['value'];
				$stations_list = views_get_view_result('view_all_station', null, $region_station , 'all');
				$stations = array();
				$stations['All'] = t('- Any -');
				foreach($stations_list as $station){
					$stations[$station->nid] = $station->node_title;
				}
				
				//danh sach cac tinh thuoc khu vucs
				$form['field_station_province_city_value']['#options'] = $provinces;
				
				//view cac lenh da thuc hien theo tung khu vuc
				/*view: thong ke lương mua
				 *view: tra cuu so lieu mua
				 *view: cac lenh da thuc hien theo tung khu vuc
				 *view: bieu do mua
				 */
				if($form['#id'] == 'views-exposed-form-view-station-rainfall-statistics-page' ||
						$form['#id'] == 'views-exposed-form-search-rainfall-page' ||
						$form['#id'] == 'views-exposed-form-view-rainfall-default-page' ||
						$form['#id'] == 'views-exposed-form-rainfall-chart-page'){
						$form['field_rainfall_station_nid']['#options'] = $stations;
				}
				/*
				if($form['#id'] == 'views-exposed-form-view-rainfall-default-page'){
					$form['field_command_station_nid']['#options'] = $stations;
				}
				*/
				//view luong mua theo tung khu vuc
				if($form['#id'] == 'views-exposed-form-view-rainfall-default-page'){
					$form['field_station_region_value']['#disabled'] = TRUE;
					$form['field_rainfall_station_nid_1']['#options'] = $stations;
				}
				
			}
		}
	}
	// dsm($form);
}
 /**
 *Begin:15/11. 
 *Implements hook_views_pre_render().
 *Author:hungnm0302
 *Description: khong hien thi thong tin admin tren view
 */	
 
function datalogger_views_pre_render(&$view) {
  if($view->name == "view_list_user") {
			for($i; $i < $view->total_rows; $i++){
				if($view->result[$i]->uid == 1){
					unset($view->result[$i]);
				}
			}
  }
	if($view->name == "view_all_station") {
		global $user;
		if (!in_array('administrator', array_values($user->roles)) && !in_array('control datalogger', array_values($user->roles))) {
			unset($view->field['nid']);
		}
	}
} 

/*
 *Implements hook_views_pre_render().
 *Author:hungnm0302
 *Description: thay đổi query hiển thị trạm theo từng khu vực trên user
 */
function datalogger_views_query_alter(&$view, &$query) {
  if($view->name == 'view_list_user' ) {
		global $user;
		$account = user_load($user->uid);
		if(in_array('administrator', array_values($user->roles))){
			$query->where[1]['conditions'][1]['value'] = array(north_central_region,mid_central_region,
							south_central_region,south_region,central_highlands);
			$query->where[1]['conditions'][1]['operator'] = 'IN';
		}
		elseif(isset($account->field_station_region['und']) && in_array('manage data', array_values($user->roles))){
			foreach($account->field_station_region['und'] as $region){
				$regions[] = $region['value'];
			}
			if(count($regions) > 1){
				$query->where[1]['conditions'][1]['value'] = $regions;
				$query->where[1]['conditions'][1]['operator'] = 'IN';
			}
			else{
				$query->where[1]['conditions'][1]['value'] = $regions;
			}
		}
  }
	//view: hien thi cac tram do mưa theo khu vuc thuc hien lenh
	//view: hien thi cac tram do mưa theo khu vuc tren ban do
	//view: hien thi cac lenh da thuc hien  theo khu vuc
	if($view->name == "view_list_stations" || $view->name == "view_map_stations" || $view->name == "view_map_alarm_stations" || $view->name == 'view_command_send_station' || $view->name == 'view_station_rainfall_statistics' || $view->name == 'rainfall_chart'||$view->name == 'search_rainfall' || $view->name == "view_modems" || $view->name == "view_rainfall_default" || $view->name == 'view_map_alarm_stations') {
		global $user;
		$account = user_load($user->uid);
		// dsm($query);
		if(in_array('administrator', array_values($user->roles))){
			$query->where[1]['conditions'][2]['value'] = array(north_central_region,mid_central_region,
							south_central_region,south_region,central_highlands);
			$query->where[1]['conditions'][2]['operator'] = 'IN';
		}
		elseif(isset($account->field_station_region['und'])){
			foreach($account->field_station_region['und'] as $region){
				$regions[] = $region['value'];
			}
			if(count($regions) > 1){
				$query->where[1]['conditions'][2]['value'] = $regions;
				$query->where[1]['conditions'][2]['operator'] = 'IN';
			}
			else{
				$query->where[1]['conditions'][2]['value'] = $regions;
			}
		}
  }
	// dsm($query);
	//view: quan ly thong tin tram
	
	if($view->name == "view_list_stations_role_manage") {
			global $user;
			if (!in_array('administrator', array_values($user->roles)) && !in_array('manage data', array_values($user->roles))) {
				$account = user_load($user->uid);
				if(isset($account->field_station_region['und'])){
					foreach($account->field_station_region['und'] as $region){
								$query->where[1]['conditions'][2]['value'] = $region['value'];
					}
				}
			}
			else{
				$query->where[1]['conditions'][2]['value'] = array(north_central_region,mid_central_region,
								south_central_region,south_region,central_highlands);
				$query->where[1]['conditions'][2]['operator'] = 'IN';
			}
  }
	
	//view: thong tin modem theo tung khu vuc dat tram
	/*
	if($view->name == "view_modems") {
		global $user;
			if (!in_array('administrator', array_values($user->roles)) && !in_array('manage data', array_values($user->roles))) {
				$account = user_load($user->uid);
				if(isset($account->field_station_region['und'])){
					foreach($account->field_station_region['und'] as $region){
								$query->where[1]['conditions'][2]['value'] = $region['value'];
					}
				}
			}
			else{
				$query->where[1]['conditions'][2]['value'] = array(north_central_region,mid_central_region,
								south_central_region,south_region,central_highlands);
				$query->where[1]['conditions'][2]['operator'] = 'IN';
			}
  }
	*/
}

/**
 * 18/10. 
 */
//module_load_include('inc', 'datalogger','datalogger.admin');
///drupal_add_js('tiles/OSM_LocalTileProxy.js', array('scope' => 'footer'));

function datalogger_action_info() {
	GLOBAL $options_commands;
  return array(
			'datalogger_send_command_action' => array(
      'type' => 'node',
      'label' => t('Send commands to multiple stations'),
      'configurable' => FALSE,
			'aggregate' => TRUE,
      'behavior' => array('changes_property'),
      'triggers' => array('node_presave', 'node_insert', 'node_update'),
    ),
  );
}

function datalogger_send_command_action(&$object, $context = array()){
	$nid;
	foreach($object as $node){
		$nid .= $node->nid.'/';
	}
	drupal_goto('command/'.$nid);
}

 /**
 * Implements hook_menu().
 */
 
function datalogger_menu() {
/**
 *Begin: 25/11. 
 *author: hungnm0302
 *description: ftp tranferer
 */		
  $items['manage/ftpserver'] = array(
    'title' => 'FPT server',
    'page callback' => '_datalogger_ftp_server',
		'file' => 'datalogger.admin.inc',
    'access callback' => TRUE,
  );

/**
 *Begin: 17/11. 
 *author: Phan Văn Tuấn
 *description: tạo menu xuất báo cáo theo năm+ngay
 */
	$items['manage/report/rainfalls/day'] = array(
    'title' => 'Daily rainfall data reports',
		'access callback' => '_datalogger_menu_access_callback_manage_data',
		'type' => MENU_DEFAULT_LOCAL_TASK, 
		'weight' => -25,
  );
	
 $items['manage/report/rainfalls'] = array(
    'title' => 'Daily rainfall data reports',
		'page callback' => 'drupal_get_form',
    'page arguments' => array(
        '_datalogger_report_rainfall_day_form'
    ),
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
		'access callback' => '_datalogger_menu_access_callback_manage_data',
		'type' => MENU_NORMAL_ITEM, 
		'weight' => -26,
	);
	
  
  $items['manage/report/rainfalls/year'] = array(
    'title' => 'Report annual rainfall data',
		'page callback' => 'drupal_get_form',
    'page arguments' => array(
        '_datalogger_report_rainfall_year_form'
    ),
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
		'access callback' => '_datalogger_menu_access_callback_manage_data',
		'type' => MENU_LOCAL_TASK,
		'weight' => -23,
  );


/**
	*Begin date:10-10-12
 *Tạo menu gọi lại menu command
 */
  $items['sendallcommand'] = array(
    // 'title' => 'Lấy giá trị lệnh trả về',
    'page callback' => '_datalogger_send_command',
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('control datalogger'),
    // 'access callback' => TRUE,
  );	
	
/**
*Begin date:10-10-12
*Tạo menu gọi lại menu command
*/
  
  $items['datalogger/command/refresh/ajax'] = array (
    'title' => 'Command',
    'page callback' => 'datalogger_command_refresh_ajax',
    'file' => 'datalogger.admin.inc',    
    'access arguments' => array('control datalogger'),
  );

	
/**
 *Begin date:09-10-12
 *kiểm tra tin nhắn mới trong bang: inbox
 */
  $items['gammu/inbox/checksms'] = array(
    'title' => 'Kiểm tra inbox',
    'page callback' => '_datalogger_check_inbox',
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
    'access callback' => TRUE,
  );
	
	$items['view/test/view'] = array(
    'title' => 'Kiem tra cac truong tren view',
    'page callback' => 'test_view',
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
    'access callback' => TRUE,
  );
  
/**
 *Begin date:03-10-12
 *tạo dữ liệu Mưa.
 */
  $items['gammu/inbox/new'] = array(
    // 'title' => 'Tin nhắn mới cập nhật',
    //'title' => 'New messages update',    
    'title' => 'Check new messages',
    // 'page arguments' => array('_new_sms_form'),
    'page callback' => '_datalogger_new_sms_form',
    // 'page callback' => '_new_sms_form',

    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
    'access callback' => TRUE,
  );
  
  // this inserts an sms remotely from another server
  $items['gammu/inbox/remote'] = array(    
    'title' => 'Gammu Inbox Remotely',
    'page callback' => '_datalogger_gammu_inbox_remote',    
    'file' => 'datalogger.admin.sms.inc',    
    'access callback' => TRUE,
  );
 
/**
 *Begin date:12-09-12
 *tạo dữ liệu Mưa.
 */
  $items['manage/user'] = array(
    'title' => 'Quản lý thông tin người dùng',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_user_form'),
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
		'access callback' => '_datalogger_menu_access_callback_manage_data',
    // 'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,  
  );
  
  $items['manage/user/user'] = array(
    'title' => 'Quản lý quyền hạn',
    // 'title' => 'User',
    // 'page callback' => 'drupal_get_form',
    // 'page arguments' => array('_user_form'),
    // 'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
		'access callback' => '_datalogger_menu_access_callback_manage_data',
    // // 'access callback' => TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,   
    
  );
  $items['manage/user/group'] = array(
    'title' => 'Quản lý nhóm',   
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_user_group_form'),
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
		'access callback' => '_datalogger_menu_access_callback_manage_data',
    'type' => MENU_LOCAL_TASK,
    'weight' => -25,
  );
   
  $items['manage/user/pass'] = array(
    'title' => 'Quản lý password',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_user_pass_form'),
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
		'access callback' => '_datalogger_menu_access_callback_manage_data',
    // 'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => -24,
  );
   
  $items['manage/user/profile'] = array(
    'title' => 'Quản lý profile',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_user_profile_form'),
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
		'access callback' => '_datalogger_menu_access_callback_manage_data',
    // 'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => -23,
  ); 
  // $items['manage/user/add'] = array(
    // 'title' => 'Tạo người dùng',
    // 'page callback' => 'drupal_get_form',
    // 'page arguments' => array('_user_add_form'),
    // 'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
    // // 'access callback' => TRUE,
    // 'type' => MENU_LOCAL_TASK,
    // 'weight' => -22,
  // ); 
  
 
	/**
	 *Begin date:11-09-12
	 *tạo dữ liệu Mưa.
	 */

 /*nhat ki tich hop du lieu*/
 $items['manage/log/rainfall'] = array(
    // 'title' => 'Nhật ký tích hợp số liệu',
    'title' => 'Integrated log data',
    'page callback' => '_log_rainfall_form',
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
		'access callback' => '_datalogger_menu_access_callback_manage_data',
  );
 
 $items['manage/report/rainfalls/month'] = array(
    'title' => 'Report monthly rainfall data',
		'page callback' => 'drupal_get_form',
    'page arguments' => array(
        '_datalogger_report_rainfall_month_form'
    ),
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
		'access callback' => '_datalogger_menu_access_callback_manage_data',
		 'type' => MENU_LOCAL_TASK,
		 'weight' => -24,
  );
 
  $items['manage/init/rainfalls'] = array(
    'title' => 'Tạo lượng mưa',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_datalogger_generate_rainfalls_form'),
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
		'access callback' => '_datalogger_menu_access_callback_manage_data',
  );
  
	/**
	 *Begin date:09-09-12
	 *phát triển giao diện quản lý dữ liệu
	 */
  $items['manage/data'] = array(
    'title' => 'Quản lý dữ liệu',
    'page callback' => '_manage_data',
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),
    'access callback' => '_datalogger_menu_access_callback_manage_data',
  );
  
  // $items['node/%node'] = array(
    // 'title' => 'Thông tin trạm đo Mưa',
    // 'title callback' => '_set_title_node',
    // 'title arguments' => array(1),
    // 'page callback' => 'drupal_get_form',
    // 'page arguments' => array('_manage_statistics_form',1),
    // // 'access callback' => TRUE,
    // 'access arguments' => array('manage data'),
    // 'description' => 'Thông tin tram',
    // 'file' => 'datalogger.admin.inc',
    // 'type' => MENU_NORMAL_ITEM,
  // );
  
  /*$items['node/%node/statistics'] = array(
    'title' => 'Thống kê',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_manage_statistics_form', 1),
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data', 1),
    'access callback' => '_datalogger_menu_access_callback_node',
    'description' => 'Thống kê lượng Mưa',
    'type' => MENU_LOCAL_TASK,
    'weight' => -25,
  );
   
  $items['node/%node/chart'] = array(
    'title' => 'Biểu đồ',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_manage_chart_form',1),
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data', 1),
    'access callback' => '_datalogger_menu_access_callback_node',
    // 'access callback' => TRUE,
    'description' => 'Biểu đồ lượng Mưa',
    'type' => MENU_LOCAL_TASK,
    'weight' => -24,
  );
   
  $items['node/%node/rainfall'] = array(
    'title' => 'Chi tiết lượng Mưa',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_manage_rainfall_form',1),
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data', 1),
    'access callback' => '_datalogger_menu_access_callback_node',
    'description' => 'Chi tiết lượng Mưa',
    'type' => MENU_LOCAL_TASK,
    'weight' => -23,
  );*/
  
  
  
/**
 *Begin date:old
 */
  $items['create/stations'] = array(
      'title' => t('Station'),
      'page callback' => '_datalogger_nodes',
      'file' => 'datalogger.admin.inc',
      'access callback' => TRUE
  );

  $items['command'] = array(
    'title' => t('Command'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
        '_command_form'
    ),
    'file' => 'datalogger.admin.inc',
    // 'access callback' => TRUE
    'access callback' => '_datalogger_menu_access_callback_command',
    //'access arguments' => array('administrator', 'control datalogger'),    
  );
  
  
  $items['logs'] = array(
      'title' => t('Logs'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array(
          '_log_nodes'
      ),
      'file' => 'datalogger.admin.inc',
      'access callback' => TRUE
  );

  $items['view/stations'] = array(
      'title' => t('List All Station'),
      'page callback' => '_view_translate_station',
      'file' => 'datalogger.admin.inc',
      'access callback' => TRUE
  );

  $items['view/logs'] = array(
      'title' => t('Log Manage'),
      'page callback' => '_view_translate_log',
      'file' => 'datalogger.admin.inc',
      'access callback' => TRUE
  );
 
  $items['phpexcel'] = array(
      'title' => t('Export to excel'),
      'page callback' => '_export_excel',
      'file' => 'datalogger.admin.excel.inc',
      'access callback' => TRUE
  );
 
  return $items;
}


function _datalogger_menu_access_callback_node($permission, $node) {
  return user_access($permission) && $node->type == 'station';
}

function _datalogger_menu_access_callback_command() {
  return (user_access('administrator') || user_access('control datalogger'));
}

function _datalogger_menu_access_callback_manage_data() {
  return user_access('manage data')|| user_access('khuvucbactrungbo')|| user_access('khuvuctrungtrungbo')|| user_access('khuvucnamtrungbo')|| user_access('khuvucnambo')|| user_access('khuvuctaynguyen');
}

/**
 * Implements hook_permission().
 */
 
function datalogger_permission() {
  return array(
    'manage data' => array(
      'title' => t('Manage data'), 
      'description' => t('Perform manage data.'),
      'restrict access' => TRUE,
    ),
		
    'control datalogger' => array(
      'title' => t('Control Datalogger'), 
      'description' => t('Perform control datalogger.'),
      'restrict access' => TRUE,
    ),
		
    'khuvucbactrungbo' => array(
      'title' => t('khuvucbactrungbo'), 
      'description' => t('Perform khuvucbactrungbo.'),
      'restrict access' => TRUE,
    ),
		
    'khuvuctrungtrungbo' => array(
      'title' => t('khuvuctrungtrungbo'), 
      'description' => t('Perform khuvuctrungtrungbo.'),
      'restrict access' => TRUE,
    ),
		
    'khuvucnamtrungbo' => array(
      'title' => t('khuvucnamtrungbo'), 
      'description' => t('Perform khuvucnamtrungbo.'),
      'restrict access' => TRUE,
    ),
		
    'khuvucnambo' => array(
      'title' => t('khuvucnambo'), 
      'description' => t('Perform khuvucnambo.'),
      'restrict access' => TRUE,
    ),
		
    'khuvuctaynguyen' => array(
      'title' => t('khuvuctaynguyen'), 
      'description' => t('Perform khuvuctaynguyen.'),
      'restrict access' => TRUE,
    ),
		
  );
}

/**
 * Implements hook_menu_alter().
 */
function datalogger_menu_alter(&$items) {
	// dsm($items);
	// /*
	if($items['node/%pm_arg/thong-ke']['page arguments'][0] == 'panel_tram_thong_ke_luong_mua'){
		// dsm(arg(1));
		// dsm($items['node/%pm_arg/thong-ke']['page arguments'][0]);
		// dsm($items['node/%pm_arg/thong-ke']['load arguments'][2]);
		$station = node_load(arg(1));
		// dsm('into');
		if($station->type != 'station'){
			unset($items['node/%pm_arg/thong-ke']);
			$items['node/%pm_arg/thong-ke']['access callback'] = FALSE;
		}
	}
	// */
	// dsm($items);
  // $items['node/%pm_arg/thong-ke']['title callback'] = '_datalogger_station_statitics';
  // $items['node/%pm_arg/thong-ke']['title arguments'] = array(1); 
	
  // $items['node/%node/thong-ke']['access arguments'] = array(1); 
	
	$items['node/%node/view']['title callback'] = '_datalogger_station_title_callback';
  $items['node/%node/view']['title arguments'] = array(1);
} 

function _datalogger_station_statitics($node) {
  if ($node->type == 'station' ) {
		// drupal_set_title(t('Station infomation: ').$node->title);
    // return t('Station infomation');
  }
  else {
    return t('View');
  }
}

function _datalogger_station_title_callback($node) {
  if ($node->type == 'station' ) {
		drupal_set_title(t('Station infomation: ').$node->title);
    return t('Station infomation');
  }
  else {
    return t('View');
  }
}

/*
 * Implements hook_openlayers_map_alter().
 */
function datalogger_openlayers_map_alter(&$map) {
  if (isset($map['layers']['mapquest_osm_offline'])) {
    $map['layers']['mapquest_osm_offline']['url'][0] = '/tiles/${z}/${x}/${y}.png';     // set local URL using special hard coded format.
    $map['layers']['mapquest_osm_offline']['serverResolutions'] = array();              // empty the array
  }
}

function _datalogger_return_area($arg = null){
	$areas = array(
		north_central_region => t('North Central Region'),
		mid_central_region  => t('Central Central Region'),  
		south_central_region  => t('South Central Region'),
		south_region => t('South Region'),
		central_highlands => t('Central Highlands Region'),
	);
	if(empty($arg) || $arg == Null || $arg == ''){
		return $areas;
	}
	return $areas[$arg];
}

function _datalogger_return_city($arg = null){
	/*
	$provinces = array(
		// ho_chi_minh => ('Ho Chi Minh'),
		// hai_phong => ('Hai Phong'),
		// ha_giang => ('Ha Giang'),
		// cao_bang => ('Cao Bang'),
		// lai_chau => ('Lai Chau'),
		// lao_cai => ('Lao Cai'),
		// tuyen_quang => ('Tuyen Quang'),
		// lang_son => ('Lang Son'),
		// bac_kan => ('Bac Kan'),
		// thai_nguyen => ('Thai Nguyen'),
		// yen_bai => ('Yen Bai'),
		// son_la => ('Son La'),
		// phu_tho => ('Phu Tho'),
		// vinh_phuc => ('Vinh Phuc'),
		// quang_ninh => ('Quang Ninh'),
		// bac_giang => ('Bac Giang'),
		// bac_ninh => ('Bac Ninh'),
		// ha_noi => ('Ha Noi'),
		// hai_duong => ('Hai Duong'),
		// hung_yen => ('Hung Yen'),
		// hoa_binh => ('Hoa Binh'),
		// ha_nam => ('Ha Nam'),
		// nam_dinh => ('Nam Dinh'),
		// thai_binh => ('Thai Binh'),
		// ninh_binh => ('Ninh Binh'),
		// dong_nai => ('Dong Nai'),
		// long_an => ('Long An'),
		// bac_lieu => ('Bac Lieu'),
		// dien_bien => ('Dien Bien'),
		// paging0 => '------------------',				
		// north_central_region => array(
			thanh_hoa => ('Thanh Hóa'),
			nghe_an => ('Nghệ An'),
			ha_tinh => ('Hà Tĩnh'),
		// ),
		// paging1 => '------------------',
		// mid_central_region => array(
			quang_binh => ('Quảng Bình'),
			quang_tri => ('Quảng Trị'),
			thua_thien_hue => ('Thừa Thiên - Huế'),
			da_nang => ('Đà Nẵng'),
			quang_nam => ('Quảng Nam'),
			quang_ngai => ('Quảng Ngãi'),
		// ),
		// paging2 => '------------------',
		// south_central_region => array(
			binh_dinh => ('Bình Định'),
			phu_yen => ('Phú Yên'),
			khanh_hoa => ('Khánh Hòa'),
			ninh_thuan => ('Ninh Thuận'),
			binh_thuan => ('Bình Thuận'),
		// ),
		// paging3 => '------------------',
		// south_region => array(
			binh_duong => ('Bình Dương'),
			tay_ninh => ('Tây Ninh'),
			tien_gian => ('Tiền Giang'),
			tra_vinh => ('Trà Vinh'),
			can_tho => ('Cần Thơ'),
			soc_trang => ('Sóc Trăng'),
			dong_thap => ('Đồng Tháp'),
			binh_phuoc => ('Bình Phước'),
			an_giang => ('An Giang'),
			kien_giang => ('Kiên Giang'),
			ca_mau => ('Cà Mau'),
			ben_tre => ('Bến Tre'),
			ba_ria_vung_tau => ('Bà Rịa - Vũng Tàu'),
			vinh_long => ('Vĩnh Long'),
			hau_giang => ('Hậu Giang'),
		// ),
		// paging4 => '------------------',
		// central_highlands  => array(
			lam_dong => ('Lâm Đồng'),
			kom_tum => ('Kon Tum'),
			giai_lai => ('Gia Lai'),
			dak_lak => ('Đắk Lắk'),
			dak_nong => ('Đắk Nông'),
		// ),
	);
	*/
	// */
	$areas = _datalogger_return_city2(null);
	$provinces = array();
	foreach($areas as $area){
		$provinces = array_merge($provinces, $area);
	}
	if(empty($arg) || $arg == Null || $arg == ''){
		return $provinces;
	}
	return $provinces[$arg];
}

function _datalogger_return_city2($arg = null){
	$provinces = array(
		north_central_region => array(
			thanh_hoa => ('Thanh Hóa'),
			nghe_an => ('Nghệ An'),
			ha_tinh => ('Hà Tĩnh'),
		),
		// paging1 => '------------------',
		mid_central_region => array(
			quang_binh => ('Quảng Bình'),
			quang_tri => ('Quảng Trị'),
			thua_thien_hue => ('Thừa Thiên - Huế'),
			da_nang => ('Đà Nẵng'),
			quang_nam => ('Quảng Nam'),
			quang_ngai => ('Quảng Ngãi'),
		),
		// paging2 => '------------------',
		south_central_region => array(
			binh_dinh => ('Bình Định'),
			phu_yen => ('Phú Yên'),
			khanh_hoa => ('Khánh Hòa'),
			ninh_thuan => ('Ninh Thuận'),
			binh_thuan => ('Bình Thuận'),
		),
		// paging3 => '------------------',
		south_region => array(
			binh_duong => ('Bình Dương'),
			tay_ninh => ('Tây Ninh'),
			tien_gian => ('Tiền Giang'),
			tra_vinh => ('Trà Vinh'),
			can_tho => ('Cần Thơ'),
			soc_trang => ('Sóc Trăng'),
			dong_thap => ('Đồng Tháp'),
			binh_phuoc => ('Bình Phước'),
			an_giang => ('An Giang'),
			kien_giang => ('Kiên Giang'),
			ca_mau => ('Cà Mau'),
			ben_tre => ('Bến Tre'),
			ba_ria_vung_tau => ('Bà Rịa - Vũng Tàu'),
			vinh_long => ('Vĩnh Long'),
			hau_giang => ('Hậu Giang'),
		),
		// paging4 => '------------------',
		central_highlands  => array(
			lam_dong => ('Lâm Đồng'),
			kom_tum => ('Kon Tum'),
			giai_lai => ('Gia Lai'),
			dak_lak => ('Đắk Lắk'),
			dak_nong => ('Đắk Nông'),
		),
	);
	if(empty($arg) || $arg == Null || $arg == ''){
		return $provinces;
	}
	return $provinces[$arg];
}
