<?php
/**
 *Begin: 16/11. 
 *author:Nguyễn Mạnh Hùng
 */
function _datalogger_return_area(){
		return array(
      north_central_region => t('Khu Vực Bắc Trung Bộ'),
			mid_central_region => t('Khu Vực Trung Trung Bộ'),
			central_highlands =>t('Khu Vực Tây Nguyên'),
			south_central_region => t('Khu Vực Nam Trung Bộ'),
			south_region => t('Khu Vực Nam Bộ'),
    );
}

function _datalogger_return_city(){
		return  array(
        ho_chi_minh => t('TP. Hồ Chí Minh'),
				hai_phong => t('TP. Hải Phòng'),
				da_nang => t('TP. Đà Nẵng'),
				ha_giang => t('Tỉnh Hà Giang'),
				cao_bang => t('Tỉnh Cao Bằng'),
				lai_chau => t('Tỉnh Lai Châu'),
				lao_cai => t('Tỉnh Lào Cai'),
				tuyen_quang => t('Tỉnh Tuyên Quang'),
				lang_son => t('Tỉnh Lạng Sơn'),
				bac_kan => t('Tỉnh Bắc Kạn'),
				thai_nguyen => t('Tỉnh Thái Nguyên'),
				yen_bai => t('Tỉnh Yên Bái'),
				son_la => t('Tỉnh Sơn La'),
				phu_tho => t('Tỉnh Phú Thọ'),
				vinh_phuc => t('Tỉnh Vĩnh Phúc'),
				quang_ninh => t('Tỉnh Quảng Ninh'),
				bac_giang => t('Tỉnh Bắc Giang'),
				bac_ninh => t('Tỉnh Bắc Ninh'),
				ha_noi => t('TP. Hà Nội'),
				hai_duong => t('Tỉnh Hải Dương'),
				hung_yen => t('Tỉnh Hưng Yên'),
				hoa_binh => t('Tỉnh Hòa Bình'),
				ha_nam => t('Tỉnh Hà Nam'),
				nam_dinh => t('Tỉnh Nam Định'),
				thai_binh => t('Tỉnh Thái Bình'),
				ninh_binh => t('Tỉnh Ninh Bình'),
				thanh_hoa => t('Tỉnh Thanh Hóa'),
				nghe_an => t('Tỉnh Nghệ An'),
				ha_tinh => t('Tỉnh Hà Tĩnh'),
				quang_binh => t('Tỉnh Quảng Bình'),
				quang_tri => t('Tỉnh Quảng Trị'),
				thua_thien_hue => t('Tỉnh Thừa Thiên - Huế'),
				quang_nam => t('Tỉnh Quảng Nam'),
				quang_ngai => t('Tỉnh Quảng Ngãi'),
				kom_tum => t('Tỉnh Kon Tum'),
				binh_dinh => t('Tỉnh Bình Định'),
				giai_lai => t('Tỉnh Gia Lai'),
				phu_yen => t('Tỉnh Phú Yên'),
				dak_lak => t('Tỉnh Đăk Lăk'),
				khanh_hoa => t('Tỉnh Khánh Hòa'),
				lam_dong => t('Tỉnh Lâm Đồng'),
				binh_phuoc => t('Tỉnh Bình Phước'),
				binh_duong => t('Tỉnh Bình Dương'),
				ninh_thuan => t('Tỉnh Ninh Thuận'),
				tay_ninh => t('Tỉnh Tây Ninh'),
				binh_thuan => t('Tỉnh Bình Thuận'),
				dong_nai => t('Tỉnh Đồng Nai'),
				long_an => t('Tỉnh Long An'),
				dong_thap => t('Tỉnh Đồng Tháp'),
				an_giang => t('Tỉnh An Giang'),
				ba_ria_vung_tau => t('Tỉnh Bà Rịa - Vũng Tàu'),
				tien_gian => t('Tỉnh Tiền Giang'),
				kien_giang => t('Tỉnh Kiên Giang'),
				can_tho => t('TP. Cần Thơ'),
				ben_tre => t('Tỉnh Bến Tre'),
				vinh_long => t('Tỉnh Vĩnh Long'),
				tra_vinh => t('Tỉnh Trà Vinh'),
				soc_trang => t('Tỉnh Sóc Trăng'),
				bac_lieu => t('Tỉnh Bạc Liêu'),
				ca_mau => t('Tỉnh Cà Mau'),
				dien_bien => t('Tỉnh Điện Biên'),
				dak_nong => t('Tỉnh Đăk Nông'),
				hau_giang => t('Tỉnh Hậu Giang'),
     );
}
 /**
 * Begin:15/11. 
 * Implements hook_views_pre_render().
 *khong hien thi thong tin admin
 */	
 
function datalogger_views_pre_render(&$view) {
  if($view->name == "view_list_user") {
			for($i; $i < $view->total_rows; $i++){
				if($view->result[$i]->uid == 1){
					unset($view->result[$i]);
				}
			}
  }
} 
 
/**
 * 18/10. 
 */
//module_load_include('inc', 'datalogger','datalogger.admin');
///drupal_add_js('tiles/OSM_LocalTileProxy.js', array('scope' => 'footer'));

function datalogger_action_info() {
	GLOBAL $options_commands;
  return array(
			'datalogger_send_command_action' => array(
      'type' => 'node',
      'label' => t('Send commands to multiple stations'),
      'configurable' => FALSE,
			'aggregate' => TRUE,
      'behavior' => array('changes_property'),
      'triggers' => array('node_presave', 'node_insert', 'node_update'),
    ),
  );
}

function datalogger_send_command_action(&$object, $context = array()){
	$nid;
	foreach($object as $node){
		$nid .= $node->nid.'/';
	}
	drupal_goto('command/'.$nid);
}

 /**
 * Implements hook_menu().
 */
 
function datalogger_menu() {

/**
 *Begin: 17/11. 
 *author: Phan Văn Tuấn
 *description: tạo menu xuất báo cáo theo năm
 */
  $items['manage/report/rainfalls/year'] = array(
    'title' => 'Báo cáo số liệu mưa theo năm',
		'page callback' => 'drupal_get_form',
    'page arguments' => array(
        '_report_rainfall_form_year'
    ),
    // 'page callback' => '_report_rainfall_form',
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),
  );

/**
 *author: Phan Văn Tuấn
 *description: tạo menu xuất báo cáo theo ngày
 */
  $items['manage/report/rainfalls/day'] = array(
    'title' => 'Báo cáo số liệu mưa theo ngày',
		'page callback' => 'drupal_get_form',
    'page arguments' => array(
        '_report_rainfall_form_day'
    ),
    // 'page callback' => '_report_rainfall_form',
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),
  );

/**
	*Begin date:10-10-12
 *Tạo menu gọi lại menu command
 */
  $items['sendallcommand'] = array(
    // 'title' => 'Lấy giá trị lệnh trả về',
    'page callback' => '_datalogger_send_command',
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('control datalogger'),
    // 'access callback' => TRUE,
  );	
	
/**
*Begin date:10-10-12
*Tạo menu gọi lại menu command
*/
  
  $items['datalogger/command/refresh/ajax'] = array (
    'title' => 'Command',
    'page callback' => 'datalogger_command_refresh_ajax',
    'file' => 'datalogger.admin.inc',    
    'access arguments' => array('control datalogger'),
  );

	
/**
 *Begin date:09-10-12
 *kiểm tra tin nhắn mới trong bang: inbox
 */
  $items['gammu/inbox/checksms'] = array(
    'title' => 'Kiểm tra inbox',
    'page callback' => '_datalogger_check_inbox',
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
    'access callback' => TRUE,
  );
	
	$items['view/test/view'] = array(
    'title' => 'Kiem tra cac truong tren view',
    'page callback' => 'test_view',
    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
    'access callback' => TRUE,
  );
  
/**
 *Begin date:03-10-12
 *tạo dữ liệu Mưa.
 */
  $items['gammu/inbox/new'] = array(
    // 'title' => 'Tin nhắn mới cập nhật',
    'title' => 'New messages update',
    'page callback' => 'drupal_get_form',
    // 'page arguments' => array('_new_sms_form'),
    'page callback' => '_datalogger_new_sms_form',
    // 'page callback' => '_new_sms_form',

    'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
    'access callback' => TRUE,
  );
 
/**
 *Begin date:12-09-12
 *tạo dữ liệu Mưa.
 */
  $items['manage/user'] = array(
    'title' => 'Quản lý thông tin người dùng',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_user_form'),
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),
    // 'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,  
  );
  
  $items['manage/user/user'] = array(
    'title' => 'Quản lý quyền hạn',
    // 'title' => 'User',
    // 'page callback' => 'drupal_get_form',
    // 'page arguments' => array('_user_form'),
    // 'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),
    // // 'access callback' => TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,   
    
  );
  $items['manage/user/group'] = array(
    'title' => 'Quản lý nhóm',   
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_user_group_form'),
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),
    'type' => MENU_LOCAL_TASK,
    'weight' => -25,
  );
   
  $items['manage/user/pass'] = array(
    'title' => 'Quản lý password',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_user_pass_form'),
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),
    // 'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => -24,
  );
   
  $items['manage/user/profile'] = array(
    'title' => 'Quản lý profile',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_user_profile_form'),
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),
    // 'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => -23,
  ); 
  // $items['manage/user/add'] = array(
    // 'title' => 'Tạo người dùng',
    // 'page callback' => 'drupal_get_form',
    // 'page arguments' => array('_user_add_form'),
    // 'file' => 'datalogger.admin.inc',
    // 'access arguments' => array('manage data'),
    // // 'access callback' => TRUE,
    // 'type' => MENU_LOCAL_TASK,
    // 'weight' => -22,
  // ); 
  
 
/**
 *Begin date:11-09-12
 *tạo dữ liệu Mưa.
 */
 
 
 $items['test3'] = array(
    'title' => 'Nhật ký tích hợp số liệu',
    'page callback' => '_datalogger_test3',
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),
  );

 /*nhat ki tich hop du lieu*/
 $items['manage/log/rainfall'] = array(
    'title' => 'Nhật ký tích hợp số liệu',
    'page callback' => '_log_rainfall_form',
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),
  );
 
 $items['manage/report/rainfalls'] = array(
    'title' => 'Báo cáo số liệu Mưa',
		'page callback' => 'drupal_get_form',
    'page arguments' => array(
        '_report_rainfall_form'
    ),
    // 'page callback' => '_report_rainfall_form',
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),
  );
 
  $items['manage/init/rainfalls'] = array(
    'title' => 'Tạo lượng mưa',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_datalogger_generate_rainfalls_form'),
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),  
  );
  
/**
 *Begin date:09-09-12
 *phát triển giao diện quản lý dữ liệu
 */
  $items['manage/data'] = array(
    'title' => 'Quản lý dữ liệu',
    'page callback' => '_manage_data',
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data'),
    'access callback' => ' _datalogger_menu_access_callback_manage_data',
  );
  
  // $items['node/%node'] = array(
    // 'title' => 'Thông tin trạm đo Mưa',
    // 'title callback' => '_set_title_node',
    // 'title arguments' => array(1),
    // 'page callback' => 'drupal_get_form',
    // 'page arguments' => array('_manage_statistics_form',1),
    // // 'access callback' => TRUE,
    // 'access arguments' => array('manage data'),
    // 'description' => 'Thông tin tram',
    // 'file' => 'datalogger.admin.inc',
    // 'type' => MENU_NORMAL_ITEM,
  // );
  
  /*$items['node/%node/statistics'] = array(
    'title' => 'Thống kê',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_manage_statistics_form', 1),
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data', 1),
    'access callback' => '_datalogger_menu_access_callback_node',
    'description' => 'Thống kê lượng Mưa',
    'type' => MENU_LOCAL_TASK,
    'weight' => -25,
  );
   
  $items['node/%node/chart'] = array(
    'title' => 'Biểu đồ',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_manage_chart_form',1),
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data', 1),
    'access callback' => '_datalogger_menu_access_callback_node',
    // 'access callback' => TRUE,
    'description' => 'Biểu đồ lượng Mưa',
    'type' => MENU_LOCAL_TASK,
    'weight' => -24,
  );
   
  $items['node/%node/rainfall'] = array(
    'title' => 'Chi tiết lượng Mưa',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_manage_rainfall_form',1),
    'file' => 'datalogger.admin.inc',
    'access arguments' => array('manage data', 1),
    'access callback' => '_datalogger_menu_access_callback_node',
    'description' => 'Chi tiết lượng Mưa',
    'type' => MENU_LOCAL_TASK,
    'weight' => -23,
  );*/
  
  
  
/**
 *Begin date:old
 */
  $items['create/stations'] = array(
      'title' => t('Station'),
      'page callback' => '_datalogger_nodes',
      'file' => 'datalogger.admin.inc',
      'access callback' => TRUE
  );

  $items['command'] = array(
    'title' => t('Command'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
        '_command_form'
    ),
    'file' => 'datalogger.admin.inc',
    // 'access callback' => TRUE
    'access callback' => '_datalogger_menu_access_callback_command',
    //'access arguments' => array('administrator', 'control datalogger'),    
  );
  
  
  $items['logs'] = array(
      'title' => t('Logs'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array(
          '_log_nodes'
      ),
      'file' => 'datalogger.admin.inc',
      'access callback' => TRUE
  );

  $items['view/stations'] = array(
      'title' => t('List All Station'),
      'page callback' => '_view_translate_station',
      'file' => 'datalogger.admin.inc',
      'access callback' => TRUE
  );

  $items['view/logs'] = array(
      'title' => t('Log Manage'),
      'page callback' => '_view_translate_log',
      'file' => 'datalogger.admin.inc',
      'access callback' => TRUE
  );
 
  $items['phpexcel'] = array(
      'title' => t('Export to excel'),
      'page callback' => '_export_excel',
      'file' => 'datalogger.admin.excel.inc',
      'access callback' => TRUE
  );
 
  return $items;
}


function _datalogger_menu_access_callback_node($permission, $node) {
  //dpm($permission);
  //dpm($node);

  return user_access($permission) && $node->type == 'station';
}

function _datalogger_menu_access_callback_command() {
  //dpm($permission);
  //dpm($node);
  return (user_access('administrator') || user_access('control datalogger'));
}

function _datalogger_menu_access_callback_manage_data() {
  //dpm($permission);
  //dpm($node);
  // if(!user_access('administrator') && !user_access('control datalogger')){
      // $user_acc = true;
  // }
  // dpm( $user_acc);
  return user_access('manage data') || $user_acc;
}

/**
 * Implements hook_permission().
 */
 
function datalogger_permission() {
  return array(
    'manage data' => array(
      'title' => t('Manage data'), 
      'description' => t('Perform manage data.'),
      'restrict access' => TRUE,
    ),
    'control datalogger' => array(
      'title' => t('Control Datalogger'), 
      'description' => t('Perform control datalogger.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_menu_alter().
 */
function datalogger_menu_alter(&$items) {
  $items['node/%node/view']['title callback'] = '_datalogger_station_title_callback';
  $items['node/%node/view']['title arguments'] = array(1);
} 

function _datalogger_station_title_callback($node) {
  if ($node->type == 'station' ) {
		drupal_set_title(t('Station infomation: ').$node->title);
    return t('Station infomation');
  }
  else {
    return t('View');
  }
}

/*
 * Implements hook_openlayers_map_alter().
 */
function datalogger_openlayers_map_alter(&$map) {
  if (isset($map['layers']['mapquest_osm_offline'])) {
    $map['layers']['mapquest_osm_offline']['url'][0] = '/tiles/${z}/${x}/${y}.png';     // set local URL using special hard coded format.
    $map['layers']['mapquest_osm_offline']['serverResolutions'] = array();              // empty the array
  }
}

/*
 * Implements hook_views_pre_render().
 */
 /*
function datalogger_views_pre_render(&$view) {
  global $user;
  //dpm($view);
  switch ($view->name) {
  case 'view_control_province':
    if (!in_array('control datalogger', $user->roles)) {      // control visible sending command field
      unset($view->field['views_bulk_operations']);    
      unset($view->field['nid']);
    }  
    // now temporary remove sending multiple stations:
    unset($view->field['views_bulk_operations']);
  }
  
}*/
